name: Build

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
  build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install poppler-utils
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go get .
      - name: Build
        run: go build -v ./...
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: binary