name: Build

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
  build:
    needs: run-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - run: sudo apt install poppler-utils
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go get .
      - run: mkdir _build
      - name: Build Linux
        run: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -v -o _build/pdf2image-linux-${{ matrix.arch }} ./cmd/pdf2image
      - name: Build macOS
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=${{ matrix.arch }} go build -v -o _build/pdf2image-mac-${{ matrix.arch }} ./cmd/pdf2image
      - name: Build Windows
        run: CGO_ENABLED=0 GOOS=windows GOARCH=${{ matrix.arch }} go build -v -o _build/pdf2image-windows-${{ matrix.arch }}.exe ./cmd/pdf2image
      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: pdf2image-linux-${{ matrix.arch }}
          path: _build/pdf2image-linux-${{ matrix.arch }}
      - name: Upload macOS binary
        uses: actions/upload-artifact@v2
        with:
          name: pdf2image-mac-${{ matrix.arch }}
          path: _build/pdf2image-mac-${{ matrix.arch }}
      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: pdf2image-windows-${{ matrix.arch }}.exe
          path: _build/pdf2image-windows-${{ matrix.arch }}.exe