name: Run Tests

on: [push, workflow_call]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install poppler-utils
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go get .
      - name: Run tests
        run: go test -v ./...
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.json